name: Release
on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed
    branches:
      - main
jobs:
  vimdoc:
    runs-on: ubuntu-22.04
    if: ${{ github.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Generate vimdoc
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: emission.nvim
          version: "Neovim >= 0.10.2"
          demojify: true
          treesitter: true
          dedupsubheadings: false # Add heading to subheading anchor links to ensure that subheadings are unique
          docmapping: true # Use h4 headers as mapping docs
      - name: PR new vimdoc
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs(vimdoc): auto generate"
          branch: ${{ github.head_ref }}
  release-pr:
    needs: vimdoc
    runs-on: ubuntu-22.04
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/release-please/config.json
          manifest-file: .github/release-please/manifest.json
